### ISSUE TITLE
[BUG] Incorrect remaining rate limit calculation

### ISSUE THREAD

**Issue by VasilVelikov** [etsy/open-api#182]
**Describe the bug**
When accessing public resources with OAuth2 access token the rate limit is calculated as if the API call is made with API key authorization only. This way the number of calls to public resources is limited to a total of 10,000 per day, no matter how many different access tokens are used.

**Additional context**
This bug is a duplicate of #154 . #154 was closed but the issue is still unresolved. I cannot re-open the previous bug so I have opened this one to avoid losing track of the problem. Please read #154 for full details about the issue.

**Comment by VasilVelikov** [comment]
@etsyachristensen 
Can you please provide an update on this issue? I tested it today and the bug is still there. This is a 100% blocker for any kind of migration to the new API.
Thank you

**Comment by VasilVelikov** [comment]
Can someone else confirm that they experience the same behavior?

Etsy team, did you manage to reproduce this issue?

**Comment by x-bass** [comment]
This bug still exists

**Comment by twidom** [comment]
Confirmed that we are also experiencing this bug.

**Comment by benjymouse** [comment]
@etsyachristensen - we're still experiencing this issue too. could you please check on the status? thx!

**Comment by etsyachristensen** [comment]
@benjymouse how recently have you seen this issue? A fix was pushed into production yesterday I think.

**Comment by benjymouse** [comment]
@etsyachristensen yes sir. we still get 429 status code fetching data against public resources

**Comment by twidom** [comment]
I've just double checked as well, and we still see this issue today, gauging this by looking at the `X-Remaining-Today` HTTP header on the HTTP responses.

**Comment by etsyachristensen** [comment]
@x-bass, @twidom, @benjymouse and @VasilVelikov . We are trying to replicate the issue you're experiencing but have so far been unable to with the latest changes that were pushed last week or so.

Could you each go to https://gist.github.com/ and make a private gist of both a public and a private call you are making including the full headers (with actual api keys and full tokens etc)? Then you can email your gist url to developers@etsy.com and reference me (Andrew Christensen) and this github issue (https://github.com/etsy/open-api/issues/182). Support should forward those to me.

Thanks!
