### ISSUE TITLE
[BUG] Broken Link: API Essentials

### ISSUE THREAD

**Issue by chris-rogala** [etsy/open-api#189]
**Describe the bug**
Broken link

**To Reproduce**
Visit [https://developers.etsy.com/documentation/](https://developers.etsy.com/documentation/) and click on API Essentials and it will send you to

> https://developers.etsy.com/documentation//essentials/oauth2/

There are two forward slashes and this is returning a 404.

**Expected behavior**
Should be directed to [https://developers.etsy.com/documentation/essentials/oauth2/](https://developers.etsy.com/documentation/essentials/oauth2/)

**Screenshots**
![image](https://user-images.githubusercontent.com/44238629/129937403-cdbbdb1e-2d7e-4345-8759-3e4738da2eb2.png)

**Additional context**
N/A

**Comment by etsyachristensen** [comment]
This has been fixed. Thanks again for your feedback!

**Comment by chris-rogala** [comment]
@etsyachristensen could be a delay in the release, but I just tested this on my phone in a private session and it is still broken

**Comment by etsyachristensen** [comment]
You're correct. Apologies. It's having trouble pushing out. Please check again tomorrow or next week.

**Comment by chris-rogala** [comment]
I’ll check again in the morning. Have a great night! If you are in New York, I hope you and your family are okay.

**Comment by chris-rogala** [comment]
@etsyachristensen It appears to have been released and is working. Thanks!
