### ISSUE TITLE
[BUG] updateListingInventory clears linked product variation images

### ISSUE THREAD

**Issue by StephanCBHall** [etsy/open-api#200]
**Describe the bug**
When updating a listings inventory via updateListingInventory after you have sent the PUT request the linked images for the listings product variations will become unlinked.

**To Reproduce**
Send PUT request using updateListingInventory endpoint to any Etsy listing with linked images

**Expected behaviour**
The listings linked images will become unlinked once the PUT request has been sent

**Comment by StephanCBHall** [comment]
Hello, I know you will be very busy with the new  API launch however this has been open for a while, is this still being investigated?

**Comment by StephanCBHall** [comment]
@etsyachristensen

**Comment by lw-andrewsmith** [comment]
+1

**Comment by etsyachristensen** [comment]
@StephanCBHall @lw-andrewsmith This has been fixed.

**Comment by etsyachristensen** [comment]
The changes had to be reverted. Need to do a bit more testing and re-deploy.

**Comment by cal-tec** [comment]
https://github.com/etsy/open-api/issues/384

**Comment by cal-tec** [comment]
Is there any chance of an update on this please?

**Comment by etsyachristensen** [comment]
Apologies for the delay but this was fixed and put into production. @cal-tec I will address you in #384.

**Comment by cal-tec** [comment]
Hi, 

Sorry to report that this issue still does not seem to be fixed and working as expected

Please see my comments and explanation on https://github.com/etsy/open-api/issues/384
