### ISSUE TITLE
[BUG]: updateShopShippingProfile says "You must provide either a carrier and mail class or min\/max delivery days."

### ISSUE THREAD

**Issue by stickfigure** [etsy/open-api#388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Trying to call updateShopShippingProfile but I get the message:

400: {"error":"You must provide either a carrier and mail class or min\/max delivery days."}

This is odd because the documentation for updateShopShippingProfile does not show the `shipping_carrier_id`, `mail_class`, or the min/max delivery days parameters. Furthermore, when I supply `shipping_carrier_id` and `mail_class`, I still get the same error message.

I'm calling `PUT https://api.etsy.com/v3/application/shops/7702729/shipping-profiles/142195376767`

Here's the body without the shipping carrier and mail class params:

```
title=My+Title&processing_time_unit=business_days&min_processing_time=1&max_processing_time=5&origin_country_iso=US&origin_postal_code=98660
```

Here's the body with the shipping carrier and mail class params:

```
title=My+Title&processing_time_unit=business_days&min_processing_time=1&max_processing_time=5&origin_country_iso=US&origin_postal_code=98660&destination_country_iso=US&shipping_carrier_id=1&mail_class=first_class
```

Both give me the same error message.

### Steps to reproduce

See bug description

### Expected behavior

Normally I'd expect this update to complete without error.

If there are additional params required, they would be in the documentation.

**Comment by stickfigure** [comment]
This seems to have resolved on its own without any code changes on my end. I'll reopen if I see it again.

**Comment by etsyachristensen** [comment]
Can you capture the headers on one of those failures so I can look it up in our system?

**Comment by stickfigure** [comment]
@etsyachristensen here's a verbose curl session, just the tokens redacted:

```
 % curl -X PUT --location "https://api.etsy.com/v3/application/shops/27293077/shipping-profiles/161078754561" \
    -H "Content-Type: application/x-www-form-urlencoded; charset=utf-8" \
    -H "X-Api-Key: <mykey>" \
    -H "Authorization: Bearer <mytoken>" \
    -d "title=The+Title&processing_time_unit=business_days&min_processing_time=1&max_processing_time=7&origin_country_iso=US&origin_postal_code=98660" -v
*   Trying 151.101.1.224:443...
* Connected to api.etsy.com (151.101.1.224) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.etsystatic.com
*  start date: Feb 14 22:59:56 2022 GMT
*  expire date: Mar 18 22:59:55 2023 GMT
*  subjectAltName: host "api.etsy.com" matched cert's "api.etsy.com"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign Atlas R3 DV TLS CA 2022 Q1
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x13b011000)
> PUT /v3/application/shops/27293077/shipping-profiles/161078754561 HTTP/2
> Host: api.etsy.com
> user-agent: curl/7.77.0
> accept: */*
> content-type: application/x-www-form-urlencoded; charset=utf-8
> x-api-key: <mykey>
> authorization: Bearer <mytoken>
> content-length: 148
> 
* We are completely uploaded and fine
< HTTP/2 400 
< server: Apache
< x-cloud-trace-context: a220ebe8a2e480f262800d99d7eee5fc/17065637738055193293;o=0
< x-etsy-request-uuid: EuXreazYILaec9QNF9sky58HGQa9
< x-limit-per-second: 20
< x-remaining-this-second: 19
< x-limit-per-day: 60000
< x-remaining-today: 59949
< set-cookie: user_prefs=<redacted>; expires=Tue, 28-Mar-2023 18:57:39 GMT; Max-Age=31536000; path=/; domain=.etsy.com
< content-type: application/json
< via: 1.1 google, 1.1 varnish
< accept-ranges: bytes
< date: Mon, 28 Mar 2022 18:57:39 GMT
< x-served-by: cache-sjc10068-SJC
< x-cache: MISS
< x-cache-hits: 0
< x-timer: S1648493860.861153,VS0,VE93
< content-length: 88
< 
{"error":"You must provide either a carrier and mail class or min\/max delivery days."}
* Connection #0 to host api.etsy.com left intact
```

**Comment by etsyachristensen** [comment]
Jeff I'm not seeing the min_delivery_days/max_delivery_days or mail_class and carrier_id in your PUT. I see the processing time but we need the min/max_delivery_days as well.

**Comment by stickfigure** [comment]
@etsyachristensen here it is with `mail_class` and `shipping_carrier_id` (which is what I assume you mean by `carrier_id`), same result:

```
% curl -X PUT --location "https://api.etsy.com/v3/application/shops/27293077/shipping-profiles/161078754561" \
    -H "Content-Type: application/x-www-form-urlencoded; charset=utf-8" \
    -H "X-Api-Key: <redacted>" \
    -H "Authorization: Bearer <redacted>" \
    -d "title=The+Title&processing_time_unit=business_days&min_processing_time=1&max_processing_time=7&origin_country_iso=US&origin_postal_code=98660&destination_country_iso=US&shipping_carrier_id=1&mail_class=first_class" -v
*   Trying 151.101.1.224:443...
* Connected to api.etsy.com (151.101.1.224) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.etsystatic.com
*  start date: Feb 14 22:59:56 2022 GMT
*  expire date: Mar 18 22:59:55 2023 GMT
*  subjectAltName: host "api.etsy.com" matched cert's "api.etsy.com"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign Atlas R3 DV TLS CA 2022 Q1
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x11f80b600)
> PUT /v3/application/shops/27293077/shipping-profiles/161078754561 HTTP/2
> Host: api.etsy.com
> user-agent: curl/7.77.0
> accept: */*
> content-type: application/x-www-form-urlencoded; charset=utf-8
> x-api-key: <redacted>
> authorization: Bearer <redacted>
> content-length: 213
> 
* We are completely uploaded and fine
< HTTP/2 400 
< server: Apache
< x-cloud-trace-context: 0bce2376a86e00de380f2d244f91a653/9956193661118507909;o=0
< x-etsy-request-uuid: Eukrqg9Ck9eV63s3EdTDldabVs58
< x-limit-per-second: 20
< x-remaining-this-second: 19
< x-limit-per-day: 60000
< x-remaining-today: 59946
< set-cookie: user_prefs=<redacted>; expires=Wed, 29-Mar-2023 00:20:01 GMT; Max-Age=31536000; path=/; domain=.etsy.com
< content-type: application/json
< via: 1.1 google, 1.1 varnish
< accept-ranges: bytes
< date: Tue, 29 Mar 2022 00:20:01 GMT
< x-served-by: cache-sjc10074-SJC
< x-cache: MISS
< x-cache-hits: 0
< x-timer: S1648513202.755907,VS0,VE88
< content-length: 88
< 
{"error":"You must provide either a carrier and mail class or min\/max delivery days."}
* Connection #0 to host api.etsy.com left intact
```

BTW the docs don't mention these parameters for updateShopShippingProfile.

**Comment by rkistaps** [comment]
Hello,
We are also facing this issue when trying to update the destination with `/v3/application/shops/26650791/shipping-profiles/{profileId}/destinations/{destinationId}`

Request 
```
{
    "primary_cost": 5.32,
    "secondary_cost": 1,
    "min_delivery_days": 3,
    "max_delivery_days": 6,
    "destination_country_iso": "US",
    "destination_region": "none",
    "shipping_carrier_id": null,
    "mail_class": null
}
```

Response
```
{
    "headers": {
        "X-Etsy-Request-Uuid": "EuMZ-24zvJ_PI21lJzHKnhKwcM22",
        "X-Limit-Per-Second": "20",
        "X-Remaining-This-Second": "15",
        "X-Limit-Per-Day": "50000",
        "X-Remaining-Today": "48948"
    },
    "data": {
        "error": "Mail class is required if carrier is present."
    }
}
```

We recently added both `shipping_carrier_id` and `mail_class` to our requests because for some customers these destinations had `shipping_carrier_id` set, but no `mail_class`. We saw that in API response, not sure how they managed that. By setting both to `null`, we hoped to avoid this error. 

This issue is quite urgent for us.

**Comment by assaflei** [comment]
@etsyachristensen I verified with a customer and it looks good 
I will update in case additional issues occur
Thanks

**Comment by rkistaps** [comment]
Yes, seems ok on our end as well. Thanks!

**Comment by rkistaps** [comment]
@etsyachristensen we just received this issue again

Request
`PUT /v3/application/shops/24965250/shipping-profiles/107895916079/destinations/22114908325`
```
{
    "primary_cost": 5.31,
    "secondary_cost": 1.82,
    "min_delivery_days": 4,
    "max_delivery_days": 10,
    "destination_country_iso": "",
    "destination_region": "eu",
    "shipping_carrier_id": null,
    "mail_class": null
}
```

Response:
```
{
    "headers": {
        "X-Etsy-Request-Uuid": "Eu5Ptl-NVfyJbKH9JsqFyhrR0s9f",
        "X-Limit-Per-Second": "20",
        "X-Remaining-This-Second": "18",
        "X-Limit-Per-Day": "50000",
        "X-Remaining-Today": "49873"
    },
    "data": {
        "error": "Mail class is required if carrier is present."
    }
}
```
Does this `X-Etsy-Request-Uuid` helps checking the issue on your end?

**Comment by etsyachristensen** [comment]
When you get a 500 error, the `X-Etsy-Request-Uuid` is very helpful. I'll look into this some more.

**Comment by stickfigure** [comment]
I don't know if this is related or not, but it's pretty weird. I just started seeing:

```
POST https://api.etsy.com/v3/application/shops/28785381/shipping-profiles

title=The+Title&primary_cost=8.87&secondary_cost=0.92&processing_time_unit=business_days&min_processing_time=1&max_processing_time=7&origin_country_iso=US&origin_postal_code=98660&destination_country_iso=US&shipping_carrier_id=1&mail_class=first_class
```

I get ` 400: {"error":"There are no supported shipping carriers for the origin country. You can only pass custom min and max delivery days."}`

Since the origin_country_iso is US, that can't be true?

**Comment by stickfigure** [comment]
@etsyachristensen the "no supported shipping carriers" error has gone away. The original "You must provide either a carrier and mail class or min\/max delivery days." is still present.

Gripe: There was apparently an unannounced breaking change that prevents BY or RU destinations from being created. Etsy should be capable of disabling these destinations internally without sending hundreds (thousands?) of developers scrambling to make code updates. I'm all in favor of the goal, but this shouldn't bleed over into APIs.

**Comment by rkistaps** [comment]
Hello. Our customers are still facing "Mail class is required if carrier is present.", while we are not providing `shipping_carrier_id` nor `mail_class`. Any solution for this would be appreciated. Thanks

**Comment by etsyachristensen** [comment]
@rkistaps Can you provide a shipping profile id or two that we can check this with? The error you are getting likely means that at some point the shipping profile had a shipping carrier defined.

Also, I noticed in your payload above that you included mail_class in the payload with a value of "null". If you aren't going to pass in a mail_class, you shouldn't include the parameter in the payload. If you want to unset the current shipping_carrier_id you should be able to pass it in as 0.

**Comment by etsyachristensen** [comment]
@stickfigure We are still looking into that error you are getting regarding the min/max. It shouldn't be giving that. Is it happening on all listings/profiles with your app or just specific ones?

As for the changes, you are correct that a change was made internally to block the RU/BY country codes from being set as destinations. This was new to all of us as we've never had to block a country before. Unfortunately this did have downstream consequences on the OpenAPI. We adjusted as quickly as we could to return a proper error code. Should any other country be blocked in the future you'll continue to receive the new error code rather than a 500.

**Comment by stickfigure** [comment]
@etsyachristensen It seems to only be that specific shop/profile: /shops/27293077/shipping-profiles/161078754561

I can call update on other profiles, and it doesn't seem to matter if the shipping_carrier_id/mail_class are present or not.

**Comment by stickfigure** [comment]
@etsyachristensen I think I've figured out what's going on. The 'US' ShippingProfileDestination for this ShippingProfile didn't have a mail class/carrier id/min/max delivery. Explicitly adding a shipping_carrier_id + mail_class to the US destination for that profile seems to fix it; I can now update the profile.

This whole thing is a bit weird. I'm guessing here, but it looks like one of the destinations (always US?) is "special" in the profile, and depending on the state of the destination, it can break updates to the profile as a whole. shipping_carrier_id/mail_class/min/max delivery days really shouldn't be part of the ShippingProfile API footprint, since they are attributes of the ShippingProfileDestination.

**Comment by rkistaps** [comment]
Hello. Thanks for your help so far, @etsyachristensen. 

As per your suggestion, I tried using `"shipping_carrier_id": 0`(instead of `"shipping_carrier_id": null`) to unset any carrier, but this gives me a new error - "You can't provide a carrier or mail class and min/max delivery days at the same time.".

Request sample
```
{
    "primary_cost": 9.99,
    "secondary_cost": 4,
    "min_delivery_days": 7,
    "max_delivery_days": 18,
    "destination_country_iso": "US",
    "destination_region": "none",
    "shipping_carrier_id": 0,
    "mail_class": null
}
```

Response
```
{
    "headers": {
        "X-Etsy-Request-Uuid": "Eu5Qet6XZLR5zgCWZVk74MDFnk13",
        "X-Limit-Per-Second": "20",
        "X-Remaining-This-Second": "18",
        "X-Limit-Per-Day": "50000",
        "X-Remaining-Today": "49887"
    },
    "data": {
        "error": "You can't provide a carrier or mail class and min/max delivery days at the same time."
    }
}
```


Some other profile ids that fail: `170102836935`, `171697066585`, `169086852958`, `115138613752`, `116122056209`.

**Comment by rkistaps** [comment]
Hello. Thanks for your help so far, @etsyachristensen. 

As per your suggestion, I tried using `"shipping_carrier_id": 0`(instead of `"shipping_carrier_id": null`) to unset any carrier and removed `mail_class`, but this gives me a new error - "You can't provide a carrier or mail class and min/max delivery days at the same time.".

Request sample
```
{
    "primary_cost": 8.81,
    "secondary_cost": 3.53,
    "min_delivery_days": 7,
    "max_delivery_days": 18,
    "destination_country_iso": "US",
    "destination_region": "none",
    "shipping_carrier_id": 0
}
```

Response
```
{
    "headers": {
        "X-Etsy-Request-Uuid": "Eu5Qet6XZLR5zgCWZVk74MDFnk13",
        "X-Limit-Per-Second": "20",
        "X-Remaining-This-Second": "18",
        "X-Limit-Per-Day": "50000",
        "X-Remaining-Today": "49887"
    },
    "data": {
        "error": "You can't provide a carrier or mail class and min/max delivery days at the same time."
    }
}
```


Some other profile ids that fail: `170102836935`, `171697066585`, `169086852958`, `115138613752`, `116122056209`.

Any other suggestions on how to update destinations for these profiles?

**Comment by rkistaps** [comment]
Hello. Adding to this issue seems like we also have problems creating listings that reference these shipping templates. It means that we cannot fix these templates and cant add new products to these templates.

Request example
```
{
    "data": {
        "is_supply": false,
        "quantity": 999,
        "title": "Radiology Shirt, X-Ray Tech Shirt, Rad Tech, Long Sleeve Shirt, Radiology Tech, Radiographer",
        "description": "some description",
        "price": 29.99,
        "state": "draft",
        "who_made": "i_did",
        "when_made": "made_to_order",
        "shipping_template_id": 147215272748,
        "taxonomy_id": 478
    },
    "params": {
        "language": "en-US"
    }
}
```

Response
```
"Error in Shipping profile: You must provide either a carrier and mail class or min\/max delivery days."
```

The only solution we see is to remove these broken templates and create a new one, but that will require us to remap all existing products to new templates which we would like to avoid. Reports are piling up on our end, any suggestion on the best course of action here?

**Comment by etsyachristensen** [comment]
@rkistaps Are you using the V2 or V3 of the OpenAPI? The data payload doesn't look like V3. It appears you're using V2. In V2 there was a big announcement made a couple months ago about new min/max delivery requirements but they only affected V2 because V3 already conformed to the new requirements. If you are using V2 this would explain your issues. And if so, this isn't something I can do anything about here as this repo is for V3. The V2 support is handled via the Etsy contact form or the Google Group (https://groups.google.com/g/etsy-api-v2).

**Comment by etsyachristensen** [comment]
> I've fixed all the profiles that were affected (there were actually several in this shop) by deleting the US destination and re-syncing (which recreates the destination). Presumably these old destinations were created before mail_class/shipping_carrier_id was required for destinations.

All of this is because of the announced change that we believed would only affect V2 users regarding the min/max delivery requirements.

Our fulfillment team put out a patch recently that should also not validate the profile itself when attempting to add destinations. That is why you were getting that message. The profile itself needed to be correct but wasn't. Likely as not the profiles were created prior to V3 so those fields were not required. That shouldn't be an issue moving forward.

Sorry for the trouble with that.

**Comment by rkistaps** [comment]
The issue of not being able to update existing shipping profile destinations is for v3. We still cannot update some of the shipping profile destinations and receive

"You can't provide a carrier or mail class and min/max delivery days at the same time.". (see my request/response examples above)

This listing creation issue would be irrelevant if we could fix those destinations. I just mentioned that because it's another place where we face this issue, but it's not the root cause of it.

**Comment by etsyachristensen** [comment]
@rkistaps We have added a patch that should fix this issue. Can you try again and see if it's resolved on your end?

**Comment by rkistaps** [comment]
Good morning. Seems like this patch had no effect. We still see and receive multiple complaints from our customers. We will try to drop and recreate all the destinations in the profile when we see these errors.

**Comment by rkistaps** [comment]
@etsyachristensen ok, it seems like the patch did help. But I just had to remove the previously added `"shipping_carrier_id": 0`. Thanks for the help here.

**Comment by etsyachristensen** [comment]
Glad to hear that @rkistaps! Sorry for all the trouble.
