### ISSUE TITLE
[BUG]: properties not shown in UI

### ISSUE THREAD

**Issue by yovasx2** [etsy/open-api#502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

after hitting edit a property like length or width, the value_id received from an existing product is not accepted by api

```
curl --location --request PUT 'https://openapi.etsy.com/v3/application/shops/18976342/listings/1239001503/properties/47626759838' \
--header 'x-api-key: xxxxxxxx' \
--header 'Authorization: Bearer xxxxxxxx' \
--header 'Content-Type: application/json' \
--header 'Cookie: uaid=xxxxxxxx.; user_prefs=xxxxxxxx.' \
--data-raw '{
    "value_ids": [54737861735],
    "values": ["6"],
    "scale_id": 5
}'
```

response:
```
        {
            "property_id": 47626759838,
            "property_name": "Length",
            "scale_id": 5,
            "scale_name": null,
            "value_ids": [
                54737861735
            ],
            "values": [
                "6"
            ]
        }
```

as u can notice the scale_name is null and when u visit that product in etsy manager, the form is not showing the value 6 for the length, the value id is from an existing previous value for the same product with the same value

### Steps to reproduce

hit update properties with a non empty value_ids array for length (47626759838) property in fabric (6451) taxonomy, and it will be set in API but not shown in UI

### Expected behavior

I expect the properties with no suggestions to accept and ignore the value_ids array

### Additional context

It only works if I empty the value_ids (for length property), but that makes it difficult because there are some properties like the size (52047899318) in dresses taxonomy (419), which has suggested values and that put request needs to have the **value_ids** defined otherwise it's not shown in the UI (the opposite as length). It would be awesome to have length rendered when u provide a non-empty value_ids

**Comment by etsyachristensen** [comment]
I am not sure I'm following, but if you include a value_id, the system will always prioritize the id over the value string as this is a more precise identification.

We did discover on June 9 that there was some cross-talk in our caching system from our development environment into production so it's possible you saw some value ids that were actually ids from development and not from production. This issue has since been corrected. Please refresh your taxonomy data if you are storing that locally.

Let me know if it's still an issue and I'll dig in some more.

**Comment by yovasx2** [comment]
let me clarify, there are 2 types of properties with scale those with predefined values (size in dresses taxonomy) and those that are open (no predefined values, infinity of possibilities) like length, width, etc. When I send a value_id in an open property the value is not correctly set, you can appreciate that in the response above, where scale_name is null (**"scale_name": null**). I notice the workaround is to avoid sending the id for open properties and then all is set correctly, but it's difficult to distinguish on my side the open from the predefined properties, so the request is for you to ignore the value_id if the property doesn't need it (like length, width, etc) and take it into consideration where it is needed like the size property in dresses

**Comment by etsyachristensen** [comment]
Ah ok now I follow. Give me some time to figure through this. It will likely involve getting another team involved.

**Comment by yovasx2** [comment]
the result of the property in the state above: "scale_name": null, is it's not rendered in shop manager

**Comment by etsyachristensen** [comment]
Ok so this can be confusing. It is for me as well. We have two types of properties: `continuous` and `discrete` which you have referred to as "open" and "predefined" respectively.

For the Etsy web UI, essentially what we do to determine if the property/attribute is continuous (such as length) we check to see if the `scale` is empty (or null) and if the `possible_values` is empty. If this is the case, it will be treated as an input with a string value. However, if there is a scale name, there should also be options in `possible_values` making it a discrete type which means you use a value_id.

Now that all being said I have a question. When you say that the scale_name: null means it's not rendered in the shop manager, where would you expect this to appear? I'm looking at your listing 1239001503 and I don't see just "Length" anywhere. I only see the discrete attributes like Sleeve Length and Hem Length. Is there another listing with just a "Length" attribute that we can view in the shop manager listing edit page?

**Comment by yovasx2** [comment]
>where would you expect this to appear? 
That depends on the property but they appear normally above holiday and occasion fields
I named it length but it could be whatever continuous property Sleeve Length and Hem Length may work to call the API to set the scale_name as null

**Comment by etsyachristensen** [comment]
Ok sorry for the delay on this.

On that listing, when I go to edit in shop manager, I see the Sleeve Length and Hem Length as drop-down values. The values being passed in are those that you are feeding into the property via the OpenAPI. Are you saying that you are getting incorrect values in that property on the Etsy UI?

As for the scale name being null, I'll look into that one. Scale 5 is "Inches" so that should be showing that.

Unfortunately we can't make the system just use the ids. The inventory system is very complex and changing it could have disastrous consequences for other elements in the system including the Etsy UI and Etsy's own apps.

**Comment by yovasx2** [comment]
> Are you saying that you are getting incorrect values in that property on the Etsy UI?
Not really, it was having a blank value in the dropdown (but API was having a value, I think shop manager cannot render it because scale_name and scale_id are null). 

The problem is produced when I sent value_ids with content and the property is discrete all works properly (for that case) but if I sent value_ids with content (even the ids from the get endpoint) and the property is continuous the response is clearing out the scale_name and scale_id (then this makes the value not visible in the shop manager). 

I also discover another problem with this endpoint and scale that is not applying so I think this part of the system is having problems: 

PS: You cannot count on the provided example because along the time that has mutated

**Comment by etsyachristensen** [comment]
Ok now I think I get it. Thanks for the clarification. I'll work with our teams to figure out what's going on.

**Comment by yovasx2** [comment]
> Ok now I think I get it. Thanks for the clarification. I'll work with our teams to figure out what's going on.

I added this issue seems to be related: https://github.com/etsy/open-api/issues/512, scale problems

**Comment by etsyachristensen** [comment]
@yovasx2 I have deployed a fix to the system that should address this problem and the issue in #512.

**Comment by yovasx2** [comment]
I am a little confuse if the fix was for 512 why this 502 is closed. @etsyachristensen

**Comment by yovasx2** [comment]
@etsyachristensen I still have problems in the shop manager UI for this issue, the issue seems to be present yet, is will attach a video (sent via email) to demonstrate how I reproduce it, you can replace vela by hitting API directly.
Steps are hit the discrete property with a scale id and a value and then ensure that value is returned by API and then go to the shop manager to appreciate the blank field.
<img width="1346" alt="1" src="https://user-images.githubusercontent.com/3578401/179068703-2c76456b-ee1c-4a02-981f-12e48c237ead.png">
<img width="1358" alt="2" src="https://user-images.githubusercontent.com/3578401/179068719-f9246826-86fb-4609-8040-328fa32930ce.png">
<img width="1352" alt="3" src="https://user-images.githubusercontent.com/3578401/179068729-d3f733ac-fa24-470e-b73f-f31d3b2e08bc.png">

**Comment by etsyachristensen** [comment]
Ok thank you for the clarification. We can in fact duplicate this and we will get on it. At the moment though the scale name and id are at least returning as not null. So progress is made. Will update you as soon as we figure it out.

**Comment by etsyachristensen** [comment]
Ok I need to check something with you. I see in your screenshot from your app you are setting the field "Size" and choosing "UK" as the scale. However, in the screenshot from the getListingProperties endpoint, you have "Kid's shoe size" coming back as the property name. I'm concerned that while your interface is trying to send "Size" it is maybe sending the wrong property id. The problem I see is that this item is in the Fabric category (taxonomy_id 6451) which doesn't have a "Size" property option. This is why that property doesn't show up in the UI for that listing.

**Comment by yovasx2** [comment]
The UI is missleading but the prodcut is having taxonomy 1430 which has the kids' size property (https://openapi.etsy.com/v3/application/seller-taxonomy/nodes/1430/properties)
```
{
            "property_id": 54142601979,
            "name": "Kids' shoe size",
            "display_name": "Size",
            "scales": [
                {
                    "scale_id": 17,
                    "display_name": "US/CA",
                    "description": ""
                },
                {
                    "scale_id": 18,
                    "display_name": "EU",
                    "description": ""
                },
                {
                    "scale_id": 19,
                    "display_name": "UK",
                    "description": ""
                }
            ],
            "is_required": false,
            "supports_attributes": true,
            "supports_variations": true,
            "is_multivalued": false,
            "max_values_allowed": null,
            "possible_values": [
                {
                    "value_id": 1329,
                    "name": "0 (Baby)",
                    "scale_id": 17,
                    "equal_to": [
                        1370,
                        1396
                    ]
                },
                {
                    "value_id": 1330,
                    "name": "0.5 (Baby)",
                    "scale_id": 17,
                    "equal_to": [
                        1371,
                        1397
                    ]
                },
                {
                    "value_id": 1331,
                    "name": "1 (Baby)",
                    "scale_id": 17,
                    "equal_to": [
                        1371,
                        1397
                    ]
                },
                {
                    "value_id": 1332,
                    "name": "1.5 (Baby)",
                    "scale_id": 17,
                    "equal_to": [
                        1372,
                        1399
                    ]
                },
                {
                    "value_id": 1333,
                    "name": "2 (Baby)",
                    "scale_id": 17,
                    "equal_to": [
                        1372,
                        1399
                    ]
                },
                {
                    "value_id": 1334,
                    "name": "2.5 (Baby)",
                    "scale_id": 17,
                    "equal_to": [
                        1373,
                        1401
                    ]
                },
                {
                    "value_id": 1335,
                    "name": "3 (Baby)",
                    "scale_id": 17,
                    "equal_to": [
                        1373,
                        1402
                    ]
                },
                {
                    "value_id": 1336,
                    "name": "3.5 (Baby)",
                    "scale_id": 17,
                    "equal_to": [
                        1374,
                        1403
                    ]
                },
                {
                    "value_id": 1337,
                    "name": "4 (Baby)",
                    "scale_id": 17,
                    "equal_to": [
                        1374,
                        1404
                    ]
                },
                {
                    "value_id": 1338,
                    "name": "4.5 (Walker)",
                    "scale_id": 17,
                    "equal_to": [
                        1375,
                        1405
                    ]
                },
                {
                    "value_id": 1339,
                    "name": "5 (Walker)",
                    "scale_id": 17,
                    "equal_to": [
                        1375,
                        1406
                    ]
                },
                {
                    "value_id": 1340,
                    "name": "5.5 (Walker)",
                    "scale_id": 17,
                    "equal_to": [
                        1376,
                        1407
                    ]
                },
                {
                    "value_id": 1341,
                    "name": "6 (Walker)",
                    "scale_id": 17,
                    "equal_to": [
                        1377,
                        1408
                    ]
                },
                {
                    "value_id": 1342,
                    "name": "6.5 (Walker)",
                    "scale_id": 17,
                    "equal_to": [
                        1377,
                        1409
                    ]
                },
                {
                    "value_id": 1343,
                    "name": "7 (Walker)",
                    "scale_id": 17,
                    "equal_to": [
                        1378,
                        1410
                    ]
                },
                {
                    "value_id": 1344,
                    "name": "7.5 (Toddler)",
                    "scale_id": 17,
                    "equal_to": [
                        1378,
                        1379,
                        1411
                    ]
                },
                {
                    "value_id": 1345,
                    "name": "8 (Toddler)",
                    "scale_id": 17,
                    "equal_to": [
                        1379,
                        1412
                    ]
                },
                {
                    "value_id": 1346,
                    "name": "8.5 (Toddler)",
                    "scale_id": 17,
                    "equal_to": [
                        1380,
                        1413
                    ]
                },
                {
                    "value_id": 1347,
                    "name": "9 (Toddler)",
                    "scale_id": 17,
                    "equal_to": [
                        1380,
                        1414
                    ]
                },
                {
                    "value_id": 1348,
                    "name": "9.5 (Toddler)",
                    "scale_id": 17,
                    "equal_to": [
                        1381,
                        1415
                    ]
                },
                {
                    "value_id": 1349,
                    "name": "10 (Toddler)",
                    "scale_id": 17,
                    "equal_to": [
                        1382,
                        1416
                    ]
                },
                {
                    "value_id": 1350,
                    "name": "10.5 (Toddler)",
                    "scale_id": 17,
                    "equal_to": [
                        1382,
                        1417
                    ]
                },
                {
                    "value_id": 1351,
                    "name": "11 (Toddler)",
                    "scale_id": 17,
                    "equal_to": [
                        1383,
                        1418
                    ]
                },
                {
                    "value_id": 1352,
                    "name": "11.5 (Toddler)",
                    "scale_id": 17,
                    "equal_to": [
                        1385,
                        1419
                    ]
                },
                {
                    "value_id": 1353,
                    "name": "12 (Toddler)",
                    "scale_id": 17,
                    "equal_to": [
                        1386,
                        1420
                    ]
                },
                {
                    "value_id": 1354,
                    "name": "12.5 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1386,
                        1421
                    ]
                },
                {
                    "value_id": 1355,
                    "name": "13 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1387,
                        1422
                    ]
                },
                {
                    "value_id": 1356,
                    "name": "13.5 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1387,
                        1423
                    ]
                },
                {
                    "value_id": 1357,
                    "name": "1 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1388,
                        1424
                    ]
                },
                {
                    "value_id": 1358,
                    "name": "1.5 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1389,
                        1425
                    ]
                },
                {
                    "value_id": 1359,
                    "name": "2 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1389,
                        1426
                    ]
                },
                {
                    "value_id": 1360,
                    "name": "2.5 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1390,
                        1427
                    ]
                },
                {
                    "value_id": 1361,
                    "name": "3 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1390,
                        1428
                    ]
                },
                {
                    "value_id": 1362,
                    "name": "3.5 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1391,
                        1429
                    ]
                },
                {
                    "value_id": 1363,
                    "name": "4 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1392,
                        1430
                    ]
                },
                {
                    "value_id": 1364,
                    "name": "4.5 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1392,
                        1431
                    ]
                },
                {
                    "value_id": 1365,
                    "name": "5 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1393,
                        1432
                    ]
                },
                {
                    "value_id": 1366,
                    "name": "5.5 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1393,
                        1433
                    ]
                },
                {
                    "value_id": 1367,
                    "name": "6 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1394,
                        1434
                    ]
                },
                {
                    "value_id": 1368,
                    "name": "6.5 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1394,
                        1435
                    ]
                },
                {
                    "value_id": 1369,
                    "name": "7 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1395,
                        1436
                    ]
                },
                {
                    "value_id": 1370,
                    "name": "15",
                    "scale_id": 18,
                    "equal_to": [
                        1329,
                        1396
                    ]
                },
                {
                    "value_id": 1371,
                    "name": "16",
                    "scale_id": 18,
                    "equal_to": [
                        1331,
                        1397,
                        1330
                    ]
                },
                {
                    "value_id": 1372,
                    "name": "17",
                    "scale_id": 18,
                    "equal_to": [
                        1333,
                        1399,
                        1332
                    ]
                },
                {
                    "value_id": 1373,
                    "name": "18",
                    "scale_id": 18,
                    "equal_to": [
                        1335,
                        1402,
                        1334,
                        1401
                    ]
                },
                {
                    "value_id": 1374,
                    "name": "19",
                    "scale_id": 18,
                    "equal_to": [
                        1337,
                        1404,
                        1336,
                        1403
                    ]
                },
                {
                    "value_id": 1375,
                    "name": "20",
                    "scale_id": 18,
                    "equal_to": [
                        1339,
                        1406,
                        1338,
                        1405
                    ]
                },
                {
                    "value_id": 1376,
                    "name": "21",
                    "scale_id": 18,
                    "equal_to": [
                        1340,
                        1407
                    ]
                },
                {
                    "value_id": 1377,
                    "name": "22",
                    "scale_id": 18,
                    "equal_to": [
                        1342,
                        1409,
                        1341,
                        1408
                    ]
                },
                {
                    "value_id": 1378,
                    "name": "23",
                    "scale_id": 18,
                    "equal_to": [
                        1343,
                        1411,
                        1344,
                        1410
                    ]
                },
                {
                    "value_id": 1379,
                    "name": "24",
                    "scale_id": 18,
                    "equal_to": [
                        1345,
                        1412,
                        1344,
                        1411
                    ]
                },
                {
                    "value_id": 1380,
                    "name": "25",
                    "scale_id": 18,
                    "equal_to": [
                        1347,
                        1414,
                        1346,
                        1413
                    ]
                },
                {
                    "value_id": 1381,
                    "name": "26",
                    "scale_id": 18,
                    "equal_to": [
                        1348,
                        1415
                    ]
                },
                {
                    "value_id": 1382,
                    "name": "27",
                    "scale_id": 18,
                    "equal_to": [
                        1350,
                        1417,
                        1349,
                        1416
                    ]
                },
                {
                    "value_id": 1383,
                    "name": "28",
                    "scale_id": 18,
                    "equal_to": [
                        1351,
                        1418
                    ]
                },
                {
                    "value_id": 1385,
                    "name": "29",
                    "scale_id": 18,
                    "equal_to": [
                        1352,
                        1419
                    ]
                },
                {
                    "value_id": 1386,
                    "name": "30",
                    "scale_id": 18,
                    "equal_to": [
                        1354,
                        1421,
                        1353,
                        1420
                    ]
                },
                {
                    "value_id": 1387,
                    "name": "31",
                    "scale_id": 18,
                    "equal_to": [
                        1356,
                        1423,
                        1355,
                        1422
                    ]
                },
                {
                    "value_id": 1388,
                    "name": "32",
                    "scale_id": 18,
                    "equal_to": [
                        1357,
                        1424
                    ]
                },
                {
                    "value_id": 1389,
                    "name": "33",
                    "scale_id": 18,
                    "equal_to": [
                        1359,
                        1426,
                        1358,
                        1425
                    ]
                },
                {
                    "value_id": 1390,
                    "name": "34",
                    "scale_id": 18,
                    "equal_to": [
                        1361,
                        1428,
                        1360,
                        1427
                    ]
                },
                {
                    "value_id": 1391,
                    "name": "35",
                    "scale_id": 18,
                    "equal_to": [
                        1362,
                        1429
                    ]
                },
                {
                    "value_id": 1392,
                    "name": "36",
                    "scale_id": 18,
                    "equal_to": [
                        1364,
                        1431,
                        1363,
                        1430
                    ]
                },
                {
                    "value_id": 1393,
                    "name": "37",
                    "scale_id": 18,
                    "equal_to": [
                        1366,
                        1433,
                        1365,
                        1432
                    ]
                },
                {
                    "value_id": 1394,
                    "name": "38",
                    "scale_id": 18,
                    "equal_to": [
                        1368,
                        1435,
                        1367,
                        1434
                    ]
                },
                {
                    "value_id": 1395,
                    "name": "39",
                    "scale_id": 18,
                    "equal_to": [
                        1369,
                        1436
                    ]
                },
                {
                    "value_id": 1396,
                    "name": "0 (Baby)",
                    "scale_id": 19,
                    "equal_to": [
                        1329,
                        1370
                    ]
                },
                {
                    "value_id": 1397,
                    "name": "0.5 (Baby)",
                    "scale_id": 19,
                    "equal_to": [
                        1331,
                        1330,
                        1371
                    ]
                },
                {
                    "value_id": 1399,
                    "name": "1 (Baby)",
                    "scale_id": 19,
                    "equal_to": [
                        1333,
                        1332,
                        1372
                    ]
                },
                {
                    "value_id": 1401,
                    "name": "1.5 (Baby)",
                    "scale_id": 19,
                    "equal_to": [
                        1334,
                        1373
                    ]
                },
                {
                    "value_id": 1402,
                    "name": "2 (Baby)",
                    "scale_id": 19,
                    "equal_to": [
                        1335,
                        1373
                    ]
                },
                {
                    "value_id": 1403,
                    "name": "2.5 (Baby)",
                    "scale_id": 19,
                    "equal_to": [
                        1336,
                        1374
                    ]
                },
                {
                    "value_id": 1404,
                    "name": "3 (Baby)",
                    "scale_id": 19,
                    "equal_to": [
                        1337,
                        1374
                    ]
                },
                {
                    "value_id": 1405,
                    "name": "3.5 (Walker)",
                    "scale_id": 19,
                    "equal_to": [
                        1338,
                        1375
                    ]
                },
                {
                    "value_id": 1406,
                    "name": "4 (Walker)",
                    "scale_id": 19,
                    "equal_to": [
                        1339,
                        1375
                    ]
                },
                {
                    "value_id": 1407,
                    "name": "4.5 (Walker)",
                    "scale_id": 19,
                    "equal_to": [
                        1340,
                        1376
                    ]
                },
                {
                    "value_id": 1408,
                    "name": "5 (Walker)",
                    "scale_id": 19,
                    "equal_to": [
                        1341,
                        1377
                    ]
                },
                {
                    "value_id": 1409,
                    "name": "5.5 (Walker)",
                    "scale_id": 19,
                    "equal_to": [
                        1342,
                        1377
                    ]
                },
                {
                    "value_id": 1410,
                    "name": "6 (Walker)",
                    "scale_id": 19,
                    "equal_to": [
                        1343,
                        1378
                    ]
                },
                {
                    "value_id": 1411,
                    "name": "6.5 (Toddler)",
                    "scale_id": 19,
                    "equal_to": [
                        1344,
                        1378,
                        1379
                    ]
                },
                {
                    "value_id": 1412,
                    "name": "7 (Toddler)",
                    "scale_id": 19,
                    "equal_to": [
                        1345,
                        1379
                    ]
                },
                {
                    "value_id": 1413,
                    "name": "7.5 (Toddler)",
                    "scale_id": 19,
                    "equal_to": [
                        1346,
                        1380
                    ]
                },
                {
                    "value_id": 1414,
                    "name": "8 (Toddler)",
                    "scale_id": 19,
                    "equal_to": [
                        1347,
                        1380
                    ]
                },
                {
                    "value_id": 1415,
                    "name": "8.5 (Toddler)",
                    "scale_id": 19,
                    "equal_to": [
                        1348,
                        1381
                    ]
                },
                {
                    "value_id": 1416,
                    "name": "9 (Toddler)",
                    "scale_id": 19,
                    "equal_to": [
                        1349,
                        1382
                    ]
                },
                {
                    "value_id": 1417,
                    "name": "9.5 (Toddler)",
                    "scale_id": 19,
                    "equal_to": [
                        1350,
                        1382
                    ]
                },
                {
                    "value_id": 1418,
                    "name": "10 (Toddler)",
                    "scale_id": 19,
                    "equal_to": [
                        1351,
                        1383
                    ]
                },
                {
                    "value_id": 1419,
                    "name": "10.5 (Toddler)",
                    "scale_id": 19,
                    "equal_to": [
                        1352,
                        1385
                    ]
                },
                {
                    "value_id": 1420,
                    "name": "11 (Toddler)",
                    "scale_id": 19,
                    "equal_to": [
                        1353,
                        1386
                    ]
                },
                {
                    "value_id": 1421,
                    "name": "11.5 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1354,
                        1386
                    ]
                },
                {
                    "value_id": 1422,
                    "name": "12 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1355,
                        1387
                    ]
                },
                {
                    "value_id": 1423,
                    "name": "12.5 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1356,
                        1387
                    ]
                },
                {
                    "value_id": 1424,
                    "name": "13 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1357,
                        1388
                    ]
                },
                {
                    "value_id": 1425,
                    "name": "13.5 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1358,
                        1389
                    ]
                },
                {
                    "value_id": 1426,
                    "name": "1 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1359,
                        1389
                    ]
                },
                {
                    "value_id": 1427,
                    "name": "1.5 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1360,
                        1390
                    ]
                },
                {
                    "value_id": 1428,
                    "name": "2 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1361,
                        1390
                    ]
                },
                {
                    "value_id": 1429,
                    "name": "2.5 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1362,
                        1391
                    ]
                },
                {
                    "value_id": 1430,
                    "name": "3 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1363,
                        1392
                    ]
                },
                {
                    "value_id": 1431,
                    "name": "3.5 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1364,
                        1392
                    ]
                },
                {
                    "value_id": 1432,
                    "name": "4 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1365,
                        1393
                    ]
                },
                {
                    "value_id": 1433,
                    "name": "4.5 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1366,
                        1393
                    ]
                },
                {
                    "value_id": 1434,
                    "name": "5 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1367,
                        1394
                    ]
                },
                {
                    "value_id": 1435,
                    "name": "5.5 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1368,
                        1394
                    ]
                },
                {
                    "value_id": 1436,
                    "name": "6 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1369,
                        1395
                    ]
                }
            ],
            "selected_values": []
        },
```

And the product is having the good property id ()properties by listing endpoint:

```
{
            "property_id": 54142601979,
            "property_name": "Kids' shoe size",
            "scale_id": 19,
            "scale_name": "UK",
            "value_ids": [
                106281378566
            ],
            "values": [
                "1.5 (Baby)"
            ]
        }
```

the data above is describing the screenshots I shared before

**Comment by etsyachristensen** [comment]
@yovasx2 I am not able to submit values for this listing. I created the listing using taxonomy_id `1430` (Boys' Shoes). I then do the `updateListingProperty` endpoint but the value_id I'm sending is the 1401 from the seller taxonomy:
![image](https://user-images.githubusercontent.com/83842847/180044222-fa3ecfb1-ad5f-4171-9fcd-91858d4fc5d9.png)
When I submit these values:
```
value_ids=[1401]
values=["1.5 (Baby)"]
scale_id=19
```
I get the property showing up in the listing properly.

**Comment by etsyachristensen** [comment]
@yovasx2 Have you had a chance to review the above?

**Comment by yovasx2** [comment]
Api shows it but not the shop manager, that's the problem

**Comment by etsyachristensen** [comment]
Can you give me the listing id for one that you are currently seeing is missing the property in the Etsy interface?

I just checked the one that I set above and it shows in the UI for me:
![image](https://user-images.githubusercontent.com/83842847/181601733-fe2ddd3c-5232-44ca-b049-c227c25044b3.png)

**Comment by yovasx2** [comment]
sure: 1262384258 belongs to the shop: 18976342

here is some evidence how vela create it, then API is capable to show it, but the shop manager is not showing it
<img width="856" alt="Screen Shot 2022-07-28 at 18 47 06" src="https://user-images.githubusercontent.com/3578401/181655631-734062b0-5095-4149-8901-ae875e7c641b.png"><img width="767" alt="Screen Shot 2022-07-28 at 18 47 25" src="https://user-images.githubusercontent.com/3578401/181655630-11f049e0-9bbb-4461-b4a0-539149e194b2.png">
<img width="904" alt="Screen Shot 2022-07-28 at 18 48 13" src="https://user-images.githubusercontent.com/3578401/181655765-3e6bf157-a4ae-49c5-9281-f7718486e708.png">


I double checked the listing taxonomy (1430) and checked this endpoint: 
https://openapi.etsy.com/v3/application/seller-taxonomy/nodes/1430/properties which returns the same property id for size: 
54142601979, so the property is correctly set by the API

**Comment by Gareth064** [comment]
Just a random observation. Does the property show up on the actual Shop Front? Is that what this is showing?

![image](https://user-images.githubusercontent.com/22307223/181720185-a5ed87ca-8049-4108-9654-837eb084573e.png)

But what your saying is that it isn't showing in the Shop Manager?

**Comment by etsyachristensen** [comment]
Sorry for all the back and forth @yovasx2 but I just checked the getPropertiesByTaxonomyId for taxonomy id 1430. I don't see that value you used. I see value id 1370. Are you pulling that id from another product on the shop?

![image](https://user-images.githubusercontent.com/83842847/181776184-0bf09d72-eda3-4742-ba93-a9954dc0c26d.png)

Can you send a screenshot from that same api call for that shop and taxonomy id?

@Gareth064 Yes that's what he's having issues with.

**Comment by yovasx2** [comment]
https://openapi.etsy.com/v3/application/seller-taxonomy/nodes/1430/properties
```
{
    "count": 21,
    "results": [
        {
            "property_id": 200,
            "name": "Primary color",
            "display_name": "Primary color",
            "scales": [],
            "is_required": false,
            "supports_attributes": true,
            "supports_variations": true,
            "is_multivalued": false,
            "max_values_allowed": 5,
            "possible_values": [
                {
                    "value_id": 1213,
                    "name": "Beige",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 1,
                    "name": "Black",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 2,
                    "name": "Blue",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 1216,
                    "name": "Bronze",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 3,
                    "name": "Brown",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 1219,
                    "name": "Clear",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 1218,
                    "name": "Copper",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 1214,
                    "name": "Gold",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 5,
                    "name": "Gray",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 4,
                    "name": "Green",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 6,
                    "name": "Orange",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 7,
                    "name": "Pink",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 8,
                    "name": "Purple",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 1220,
                    "name": "Rainbow",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 9,
                    "name": "Red",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 1217,
                    "name": "Rose gold",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 1215,
                    "name": "Silver",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 10,
                    "name": "White",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 11,
                    "name": "Yellow",
                    "scale_id": null,
                    "equal_to": []
                }
            ],
            "selected_values": []
        },
        {
            "property_id": 52047899002,
            "name": "Secondary color",
            "display_name": "Secondary color",
            "scales": [],
            "is_required": false,
            "supports_attributes": true,
            "supports_variations": true,
            "is_multivalued": false,
            "max_values_allowed": 5,
            "possible_values": [
                {
                    "value_id": 1213,
                    "name": "Beige",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 1,
                    "name": "Black",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 2,
                    "name": "Blue",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 1216,
                    "name": "Bronze",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 3,
                    "name": "Brown",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 1219,
                    "name": "Clear",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 1218,
                    "name": "Copper",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 1214,
                    "name": "Gold",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 5,
                    "name": "Gray",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 4,
                    "name": "Green",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 6,
                    "name": "Orange",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 7,
                    "name": "Pink",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 8,
                    "name": "Purple",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 1220,
                    "name": "Rainbow",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 9,
                    "name": "Red",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 1217,
                    "name": "Rose gold",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 1215,
                    "name": "Silver",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 10,
                    "name": "White",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 11,
                    "name": "Yellow",
                    "scale_id": null,
                    "equal_to": []
                }
            ],
            "selected_values": []
        },
        {
            "property_id": 54142601979,
            "name": "Kids' shoe size",
            "display_name": "Size",
            "scales": [
                {
                    "scale_id": 17,
                    "display_name": "US/CA",
                    "description": ""
                },
                {
                    "scale_id": 18,
                    "display_name": "EU",
                    "description": ""
                },
                {
                    "scale_id": 19,
                    "display_name": "UK",
                    "description": ""
                }
            ],
            "is_required": false,
            "supports_attributes": true,
            "supports_variations": true,
            "is_multivalued": false,
            "max_values_allowed": null,
            "possible_values": [
                {
                    "value_id": 1329,
                    "name": "0 (Baby)",
                    "scale_id": 17,
                    "equal_to": [
                        1370,
                        1396
                    ]
                },
                {
                    "value_id": 1330,
                    "name": "0.5 (Baby)",
                    "scale_id": 17,
                    "equal_to": [
                        1371,
                        1397
                    ]
                },
                {
                    "value_id": 1331,
                    "name": "1 (Baby)",
                    "scale_id": 17,
                    "equal_to": [
                        1371,
                        1397
                    ]
                },
                {
                    "value_id": 1332,
                    "name": "1.5 (Baby)",
                    "scale_id": 17,
                    "equal_to": [
                        1372,
                        1399
                    ]
                },
                {
                    "value_id": 1333,
                    "name": "2 (Baby)",
                    "scale_id": 17,
                    "equal_to": [
                        1372,
                        1399
                    ]
                },
                {
                    "value_id": 1334,
                    "name": "2.5 (Baby)",
                    "scale_id": 17,
                    "equal_to": [
                        1373,
                        1401
                    ]
                },
                {
                    "value_id": 1335,
                    "name": "3 (Baby)",
                    "scale_id": 17,
                    "equal_to": [
                        1373,
                        1402
                    ]
                },
                {
                    "value_id": 1336,
                    "name": "3.5 (Baby)",
                    "scale_id": 17,
                    "equal_to": [
                        1374,
                        1403
                    ]
                },
                {
                    "value_id": 1337,
                    "name": "4 (Baby)",
                    "scale_id": 17,
                    "equal_to": [
                        1374,
                        1404
                    ]
                },
                {
                    "value_id": 1338,
                    "name": "4.5 (Walker)",
                    "scale_id": 17,
                    "equal_to": [
                        1375,
                        1405
                    ]
                },
                {
                    "value_id": 1339,
                    "name": "5 (Walker)",
                    "scale_id": 17,
                    "equal_to": [
                        1375,
                        1406
                    ]
                },
                {
                    "value_id": 1340,
                    "name": "5.5 (Walker)",
                    "scale_id": 17,
                    "equal_to": [
                        1376,
                        1407
                    ]
                },
                {
                    "value_id": 1341,
                    "name": "6 (Walker)",
                    "scale_id": 17,
                    "equal_to": [
                        1377,
                        1408
                    ]
                },
                {
                    "value_id": 1342,
                    "name": "6.5 (Walker)",
                    "scale_id": 17,
                    "equal_to": [
                        1377,
                        1409
                    ]
                },
                {
                    "value_id": 1343,
                    "name": "7 (Walker)",
                    "scale_id": 17,
                    "equal_to": [
                        1378,
                        1410
                    ]
                },
                {
                    "value_id": 1344,
                    "name": "7.5 (Toddler)",
                    "scale_id": 17,
                    "equal_to": [
                        1378,
                        1379,
                        1411
                    ]
                },
                {
                    "value_id": 1345,
                    "name": "8 (Toddler)",
                    "scale_id": 17,
                    "equal_to": [
                        1379,
                        1412
                    ]
                },
                {
                    "value_id": 1346,
                    "name": "8.5 (Toddler)",
                    "scale_id": 17,
                    "equal_to": [
                        1380,
                        1413
                    ]
                },
                {
                    "value_id": 1347,
                    "name": "9 (Toddler)",
                    "scale_id": 17,
                    "equal_to": [
                        1380,
                        1414
                    ]
                },
                {
                    "value_id": 1348,
                    "name": "9.5 (Toddler)",
                    "scale_id": 17,
                    "equal_to": [
                        1381,
                        1415
                    ]
                },
                {
                    "value_id": 1349,
                    "name": "10 (Toddler)",
                    "scale_id": 17,
                    "equal_to": [
                        1382,
                        1416
                    ]
                },
                {
                    "value_id": 1350,
                    "name": "10.5 (Toddler)",
                    "scale_id": 17,
                    "equal_to": [
                        1382,
                        1417
                    ]
                },
                {
                    "value_id": 1351,
                    "name": "11 (Toddler)",
                    "scale_id": 17,
                    "equal_to": [
                        1383,
                        1418
                    ]
                },
                {
                    "value_id": 1352,
                    "name": "11.5 (Toddler)",
                    "scale_id": 17,
                    "equal_to": [
                        1385,
                        1419
                    ]
                },
                {
                    "value_id": 1353,
                    "name": "12 (Toddler)",
                    "scale_id": 17,
                    "equal_to": [
                        1386,
                        1420
                    ]
                },
                {
                    "value_id": 1354,
                    "name": "12.5 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1386,
                        1421
                    ]
                },
                {
                    "value_id": 1355,
                    "name": "13 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1387,
                        1422
                    ]
                },
                {
                    "value_id": 1356,
                    "name": "13.5 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1387,
                        1423
                    ]
                },
                {
                    "value_id": 1357,
                    "name": "1 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1388,
                        1424
                    ]
                },
                {
                    "value_id": 1358,
                    "name": "1.5 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1389,
                        1425
                    ]
                },
                {
                    "value_id": 1359,
                    "name": "2 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1389,
                        1426
                    ]
                },
                {
                    "value_id": 1360,
                    "name": "2.5 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1390,
                        1427
                    ]
                },
                {
                    "value_id": 1361,
                    "name": "3 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1390,
                        1428
                    ]
                },
                {
                    "value_id": 1362,
                    "name": "3.5 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1391,
                        1429
                    ]
                },
                {
                    "value_id": 1363,
                    "name": "4 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1392,
                        1430
                    ]
                },
                {
                    "value_id": 1364,
                    "name": "4.5 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1392,
                        1431
                    ]
                },
                {
                    "value_id": 1365,
                    "name": "5 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1393,
                        1432
                    ]
                },
                {
                    "value_id": 1366,
                    "name": "5.5 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1393,
                        1433
                    ]
                },
                {
                    "value_id": 1367,
                    "name": "6 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1394,
                        1434
                    ]
                },
                {
                    "value_id": 1368,
                    "name": "6.5 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1394,
                        1435
                    ]
                },
                {
                    "value_id": 1369,
                    "name": "7 (Youth)",
                    "scale_id": 17,
                    "equal_to": [
                        1395,
                        1436
                    ]
                },
                {
                    "value_id": 1370,
                    "name": "15",
                    "scale_id": 18,
                    "equal_to": [
                        1329,
                        1396
                    ]
                },
                {
                    "value_id": 1371,
                    "name": "16",
                    "scale_id": 18,
                    "equal_to": [
                        1331,
                        1397,
                        1330
                    ]
                },
                {
                    "value_id": 1372,
                    "name": "17",
                    "scale_id": 18,
                    "equal_to": [
                        1333,
                        1399,
                        1332
                    ]
                },
                {
                    "value_id": 1373,
                    "name": "18",
                    "scale_id": 18,
                    "equal_to": [
                        1335,
                        1402,
                        1334,
                        1401
                    ]
                },
                {
                    "value_id": 1374,
                    "name": "19",
                    "scale_id": 18,
                    "equal_to": [
                        1337,
                        1404,
                        1336,
                        1403
                    ]
                },
                {
                    "value_id": 1375,
                    "name": "20",
                    "scale_id": 18,
                    "equal_to": [
                        1339,
                        1406,
                        1338,
                        1405
                    ]
                },
                {
                    "value_id": 1376,
                    "name": "21",
                    "scale_id": 18,
                    "equal_to": [
                        1340,
                        1407
                    ]
                },
                {
                    "value_id": 1377,
                    "name": "22",
                    "scale_id": 18,
                    "equal_to": [
                        1342,
                        1409,
                        1341,
                        1408
                    ]
                },
                {
                    "value_id": 1378,
                    "name": "23",
                    "scale_id": 18,
                    "equal_to": [
                        1343,
                        1411,
                        1344,
                        1410
                    ]
                },
                {
                    "value_id": 1379,
                    "name": "24",
                    "scale_id": 18,
                    "equal_to": [
                        1345,
                        1412,
                        1344,
                        1411
                    ]
                },
                {
                    "value_id": 1380,
                    "name": "25",
                    "scale_id": 18,
                    "equal_to": [
                        1347,
                        1414,
                        1346,
                        1413
                    ]
                },
                {
                    "value_id": 1381,
                    "name": "26",
                    "scale_id": 18,
                    "equal_to": [
                        1348,
                        1415
                    ]
                },
                {
                    "value_id": 1382,
                    "name": "27",
                    "scale_id": 18,
                    "equal_to": [
                        1350,
                        1417,
                        1349,
                        1416
                    ]
                },
                {
                    "value_id": 1383,
                    "name": "28",
                    "scale_id": 18,
                    "equal_to": [
                        1351,
                        1418
                    ]
                },
                {
                    "value_id": 1385,
                    "name": "29",
                    "scale_id": 18,
                    "equal_to": [
                        1352,
                        1419
                    ]
                },
                {
                    "value_id": 1386,
                    "name": "30",
                    "scale_id": 18,
                    "equal_to": [
                        1354,
                        1421,
                        1353,
                        1420
                    ]
                },
                {
                    "value_id": 1387,
                    "name": "31",
                    "scale_id": 18,
                    "equal_to": [
                        1356,
                        1423,
                        1355,
                        1422
                    ]
                },
                {
                    "value_id": 1388,
                    "name": "32",
                    "scale_id": 18,
                    "equal_to": [
                        1357,
                        1424
                    ]
                },
                {
                    "value_id": 1389,
                    "name": "33",
                    "scale_id": 18,
                    "equal_to": [
                        1359,
                        1426,
                        1358,
                        1425
                    ]
                },
                {
                    "value_id": 1390,
                    "name": "34",
                    "scale_id": 18,
                    "equal_to": [
                        1361,
                        1428,
                        1360,
                        1427
                    ]
                },
                {
                    "value_id": 1391,
                    "name": "35",
                    "scale_id": 18,
                    "equal_to": [
                        1362,
                        1429
                    ]
                },
                {
                    "value_id": 1392,
                    "name": "36",
                    "scale_id": 18,
                    "equal_to": [
                        1364,
                        1431,
                        1363,
                        1430
                    ]
                },
                {
                    "value_id": 1393,
                    "name": "37",
                    "scale_id": 18,
                    "equal_to": [
                        1366,
                        1433,
                        1365,
                        1432
                    ]
                },
                {
                    "value_id": 1394,
                    "name": "38",
                    "scale_id": 18,
                    "equal_to": [
                        1368,
                        1435,
                        1367,
                        1434
                    ]
                },
                {
                    "value_id": 1395,
                    "name": "39",
                    "scale_id": 18,
                    "equal_to": [
                        1369,
                        1436
                    ]
                },
                {
                    "value_id": 1396,
                    "name": "0 (Baby)",
                    "scale_id": 19,
                    "equal_to": [
                        1329,
                        1370
                    ]
                },
                {
                    "value_id": 1397,
                    "name": "0.5 (Baby)",
                    "scale_id": 19,
                    "equal_to": [
                        1331,
                        1330,
                        1371
                    ]
                },
                {
                    "value_id": 1399,
                    "name": "1 (Baby)",
                    "scale_id": 19,
                    "equal_to": [
                        1333,
                        1332,
                        1372
                    ]
                },
                {
                    "value_id": 1401,
                    "name": "1.5 (Baby)",
                    "scale_id": 19,
                    "equal_to": [
                        1334,
                        1373
                    ]
                },
                {
                    "value_id": 1402,
                    "name": "2 (Baby)",
                    "scale_id": 19,
                    "equal_to": [
                        1335,
                        1373
                    ]
                },
                {
                    "value_id": 1403,
                    "name": "2.5 (Baby)",
                    "scale_id": 19,
                    "equal_to": [
                        1336,
                        1374
                    ]
                },
                {
                    "value_id": 1404,
                    "name": "3 (Baby)",
                    "scale_id": 19,
                    "equal_to": [
                        1337,
                        1374
                    ]
                },
                {
                    "value_id": 1405,
                    "name": "3.5 (Walker)",
                    "scale_id": 19,
                    "equal_to": [
                        1338,
                        1375
                    ]
                },
                {
                    "value_id": 1406,
                    "name": "4 (Walker)",
                    "scale_id": 19,
                    "equal_to": [
                        1339,
                        1375
                    ]
                },
                {
                    "value_id": 1407,
                    "name": "4.5 (Walker)",
                    "scale_id": 19,
                    "equal_to": [
                        1340,
                        1376
                    ]
                },
                {
                    "value_id": 1408,
                    "name": "5 (Walker)",
                    "scale_id": 19,
                    "equal_to": [
                        1341,
                        1377
                    ]
                },
                {
                    "value_id": 1409,
                    "name": "5.5 (Walker)",
                    "scale_id": 19,
                    "equal_to": [
                        1342,
                        1377
                    ]
                },
                {
                    "value_id": 1410,
                    "name": "6 (Walker)",
                    "scale_id": 19,
                    "equal_to": [
                        1343,
                        1378
                    ]
                },
                {
                    "value_id": 1411,
                    "name": "6.5 (Toddler)",
                    "scale_id": 19,
                    "equal_to": [
                        1344,
                        1378,
                        1379
                    ]
                },
                {
                    "value_id": 1412,
                    "name": "7 (Toddler)",
                    "scale_id": 19,
                    "equal_to": [
                        1345,
                        1379
                    ]
                },
                {
                    "value_id": 1413,
                    "name": "7.5 (Toddler)",
                    "scale_id": 19,
                    "equal_to": [
                        1346,
                        1380
                    ]
                },
                {
                    "value_id": 1414,
                    "name": "8 (Toddler)",
                    "scale_id": 19,
                    "equal_to": [
                        1347,
                        1380
                    ]
                },
                {
                    "value_id": 1415,
                    "name": "8.5 (Toddler)",
                    "scale_id": 19,
                    "equal_to": [
                        1348,
                        1381
                    ]
                },
                {
                    "value_id": 1416,
                    "name": "9 (Toddler)",
                    "scale_id": 19,
                    "equal_to": [
                        1349,
                        1382
                    ]
                },
                {
                    "value_id": 1417,
                    "name": "9.5 (Toddler)",
                    "scale_id": 19,
                    "equal_to": [
                        1350,
                        1382
                    ]
                },
                {
                    "value_id": 1418,
                    "name": "10 (Toddler)",
                    "scale_id": 19,
                    "equal_to": [
                        1351,
                        1383
                    ]
                },
                {
                    "value_id": 1419,
                    "name": "10.5 (Toddler)",
                    "scale_id": 19,
                    "equal_to": [
                        1352,
                        1385
                    ]
                },
                {
                    "value_id": 1420,
                    "name": "11 (Toddler)",
                    "scale_id": 19,
                    "equal_to": [
                        1353,
                        1386
                    ]
                },
                {
                    "value_id": 1421,
                    "name": "11.5 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1354,
                        1386
                    ]
                },
                {
                    "value_id": 1422,
                    "name": "12 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1355,
                        1387
                    ]
                },
                {
                    "value_id": 1423,
                    "name": "12.5 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1356,
                        1387
                    ]
                },
                {
                    "value_id": 1424,
                    "name": "13 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1357,
                        1388
                    ]
                },
                {
                    "value_id": 1425,
                    "name": "13.5 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1358,
                        1389
                    ]
                },
                {
                    "value_id": 1426,
                    "name": "1 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1359,
                        1389
                    ]
                },
                {
                    "value_id": 1427,
                    "name": "1.5 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1360,
                        1390
                    ]
                },
                {
                    "value_id": 1428,
                    "name": "2 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1361,
                        1390
                    ]
                },
                {
                    "value_id": 1429,
                    "name": "2.5 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1362,
                        1391
                    ]
                },
                {
                    "value_id": 1430,
                    "name": "3 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1363,
                        1392
                    ]
                },
                {
                    "value_id": 1431,
                    "name": "3.5 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1364,
                        1392
                    ]
                },
                {
                    "value_id": 1432,
                    "name": "4 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1365,
                        1393
                    ]
                },
                {
                    "value_id": 1433,
                    "name": "4.5 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1366,
                        1393
                    ]
                },
                {
                    "value_id": 1434,
                    "name": "5 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1367,
                        1394
                    ]
                },
                {
                    "value_id": 1435,
                    "name": "5.5 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1368,
                        1394
                    ]
                },
                {
                    "value_id": 1436,
                    "name": "6 (Youth)",
                    "scale_id": 19,
                    "equal_to": [
                        1369,
                        1395
                    ]
                }
            ],
            "selected_values": []
        },
        {
            "property_id": 46803063641,
            "name": "Occasion",
            "display_name": "Occasion",
            "scales": [],
            "is_required": false,
            "supports_attributes": true,
            "supports_variations": false,
            "is_multivalued": false,
            "max_values_allowed": 5,
            "possible_values": [
                {
                    "value_id": 2773,
                    "name": "1st birthday",
                    "scale_id": null,
                    "equal_to": [
                        19
                    ]
                },
                {
                    "value_id": 12,
                    "name": "Anniversary",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 13,
                    "name": "Baby shower",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 14,
                    "name": "Bachelor party",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 15,
                    "name": "Bachelorette party",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 16,
                    "name": "Back to school",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 17,
                    "name": "Baptism",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 18,
                    "name": "Bar & Bat Mitzvah",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 19,
                    "name": "Birthday",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 20,
                    "name": "Bridal shower",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 21,
                    "name": "Confirmation",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 26,
                    "name": "Divorce & breakup",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 22,
                    "name": "Engagement",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 23,
                    "name": "First Communion",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 24,
                    "name": "Graduation",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 25,
                    "name": "Grief & mourning",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 27,
                    "name": "Housewarming",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 2774,
                    "name": "LGBTQ pride",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 50,
                    "name": "Moving",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 28,
                    "name": "Pet loss",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 29,
                    "name": "Prom",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 30,
                    "name": "Quinceañera & Sweet 16",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 31,
                    "name": "Retirement",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 32,
                    "name": "Wedding",
                    "scale_id": null,
                    "equal_to": []
                }
            ],
            "selected_values": []
        },
        {
            "property_id": 46803063659,
            "name": "Holiday",
            "display_name": "Holiday",
            "scales": [],
            "is_required": false,
            "supports_attributes": true,
            "supports_variations": false,
            "is_multivalued": false,
            "max_values_allowed": 5,
            "possible_values": [
                {
                    "value_id": 33,
                    "name": "April Fools'",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 35,
                    "name": "Christmas",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 36,
                    "name": "Cinco de Mayo",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 37,
                    "name": "Easter",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 38,
                    "name": "Father's Day",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 39,
                    "name": "Halloween",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 40,
                    "name": "Hanukkah",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 41,
                    "name": "Independence Day",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 42,
                    "name": "Kwanzaa",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 34,
                    "name": "Lunar New Year",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 43,
                    "name": "Mother's Day",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 44,
                    "name": "New Year's",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 47,
                    "name": "Passover",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 45,
                    "name": "St Patrick's Day",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 46,
                    "name": "Thanksgiving",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 48,
                    "name": "Valentine's Day",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 49,
                    "name": "Veterans Day",
                    "scale_id": null,
                    "equal_to": []
                }
            ],
            "selected_values": []
        },
        {
            "property_id": 504,
            "name": "Diameter",
            "display_name": "Diameter",
            "scales": [
                {
                    "scale_id": 341,
                    "display_name": "Inches",
                    "description": "Inches"
                },
                {
                    "scale_id": 342,
                    "display_name": "Centimeters",
                    "description": "Centimeters"
                },
                {
                    "scale_id": 343,
                    "display_name": "Other",
                    "description": "Other"
                }
            ],
            "is_required": false,
            "supports_attributes": false,
            "supports_variations": true,
            "is_multivalued": false,
            "max_values_allowed": null,
            "possible_values": [],
            "selected_values": []
        },
        {
            "property_id": 501,
            "name": "Dimensions",
            "display_name": "Dimensions",
            "scales": [
                {
                    "scale_id": 344,
                    "display_name": "Inches",
                    "description": "Inches"
                },
                {
                    "scale_id": 345,
                    "display_name": "Centimeters",
                    "description": "Centimeters"
                },
                {
                    "scale_id": 346,
                    "display_name": "Other",
                    "description": "Other"
                }
            ],
            "is_required": false,
            "supports_attributes": false,
            "supports_variations": true,
            "is_multivalued": false,
            "max_values_allowed": null,
            "possible_values": [],
            "selected_values": []
        },
        {
            "property_id": 502,
            "name": "Fabric",
            "display_name": "Fabric",
            "scales": [],
            "is_required": false,
            "supports_attributes": false,
            "supports_variations": true,
            "is_multivalued": false,
            "max_values_allowed": null,
            "possible_values": [],
            "selected_values": []
        },
        {
            "property_id": 500,
            "name": "Finish",
            "display_name": "Finish",
            "scales": [],
            "is_required": false,
            "supports_attributes": false,
            "supports_variations": true,
            "is_multivalued": false,
            "max_values_allowed": null,
            "possible_values": [],
            "selected_values": []
        },
        {
            "property_id": 503,
            "name": "Flavor",
            "display_name": "Flavor",
            "scales": [],
            "is_required": false,
            "supports_attributes": false,
            "supports_variations": true,
            "is_multivalued": false,
            "max_values_allowed": null,
            "possible_values": [],
            "selected_values": []
        },
        {
            "property_id": 505,
            "name": "Height",
            "display_name": "Height",
            "scales": [
                {
                    "scale_id": 347,
                    "display_name": "Inches",
                    "description": "Inches"
                },
                {
                    "scale_id": 348,
                    "display_name": "Centimeters",
                    "description": "Centimeters"
                },
                {
                    "scale_id": 349,
                    "display_name": "Other",
                    "description": "Other"
                }
            ],
            "is_required": false,
            "supports_attributes": false,
            "supports_variations": true,
            "is_multivalued": false,
            "max_values_allowed": null,
            "possible_values": [],
            "selected_values": []
        },
        {
            "property_id": 506,
            "name": "Length",
            "display_name": "Length",
            "scales": [
                {
                    "scale_id": 350,
                    "display_name": "Inches",
                    "description": "Inches"
                },
                {
                    "scale_id": 351,
                    "display_name": "Centimeters",
                    "description": "Centimeters"
                },
                {
                    "scale_id": 352,
                    "display_name": "Other",
                    "description": "Other"
                }
            ],
            "is_required": false,
            "supports_attributes": false,
            "supports_variations": true,
            "is_multivalued": false,
            "max_values_allowed": null,
            "possible_values": [],
            "selected_values": []
        },
        {
            "property_id": 507,
            "name": "Material",
            "display_name": "Material",
            "scales": [],
            "is_required": false,
            "supports_attributes": false,
            "supports_variations": true,
            "is_multivalued": false,
            "max_values_allowed": null,
            "possible_values": [],
            "selected_values": []
        },
        {
            "property_id": 508,
            "name": "Pattern",
            "display_name": "Pattern",
            "scales": [],
            "is_required": false,
            "supports_attributes": false,
            "supports_variations": true,
            "is_multivalued": false,
            "max_values_allowed": null,
            "possible_values": [],
            "selected_values": []
        },
        {
            "property_id": 509,
            "name": "Scent",
            "display_name": "Scent",
            "scales": [],
            "is_required": false,
            "supports_attributes": false,
            "supports_variations": true,
            "is_multivalued": false,
            "max_values_allowed": null,
            "possible_values": [],
            "selected_values": []
        },
        {
            "property_id": 510,
            "name": "Style",
            "display_name": "Style",
            "scales": [],
            "is_required": false,
            "supports_attributes": false,
            "supports_variations": true,
            "is_multivalued": false,
            "max_values_allowed": null,
            "possible_values": [],
            "selected_values": []
        },
        {
            "property_id": 511,
            "name": "Weight",
            "display_name": "Weight",
            "scales": [
                {
                    "scale_id": 332,
                    "display_name": "Pounds",
                    "description": "Pounds"
                },
                {
                    "scale_id": 331,
                    "display_name": "Ounces",
                    "description": "Ounces"
                },
                {
                    "scale_id": 333,
                    "display_name": "Grams",
                    "description": "Grams"
                },
                {
                    "scale_id": 334,
                    "display_name": "Kilograms",
                    "description": "Kilograms"
                }
            ],
            "is_required": false,
            "supports_attributes": false,
            "supports_variations": true,
            "is_multivalued": false,
            "max_values_allowed": null,
            "possible_values": [],
            "selected_values": []
        },
        {
            "property_id": 512,
            "name": "Width",
            "display_name": "Width",
            "scales": [
                {
                    "scale_id": 338,
                    "display_name": "Inches",
                    "description": "Inches"
                },
                {
                    "scale_id": 339,
                    "display_name": "Centimeters",
                    "description": "Centimeters"
                },
                {
                    "scale_id": 340,
                    "display_name": "Other",
                    "description": "Other"
                }
            ],
            "is_required": false,
            "supports_attributes": false,
            "supports_variations": true,
            "is_multivalued": false,
            "max_values_allowed": null,
            "possible_values": [],
            "selected_values": []
        },
        {
            "property_id": 515,
            "name": "Device",
            "display_name": "Device",
            "scales": [],
            "is_required": false,
            "supports_attributes": false,
            "supports_variations": true,
            "is_multivalued": false,
            "max_values_allowed": null,
            "possible_values": [
                {
                    "value_id": 5668983248,
                    "name": "iPad",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 5668983250,
                    "name": "iPad Mini",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 5668983258,
                    "name": "iPhone 5",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 5745757057,
                    "name": "iPhone 4/4S",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 5668983226,
                    "name": "Kindle Fire HD",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 5668983232,
                    "name": "Kindle Fire HD 8.9\"",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 5668983234,
                    "name": "Kindle Paperwhite",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 5668983240,
                    "name": "Samsung Galaxy S4",
                    "scale_id": null,
                    "equal_to": []
                },
                {
                    "value_id": 5668983238,
                    "name": "Samsung Galaxy S3",
                    "scale_id": null,
                    "equal_to": []
                }
            ],
            "selected_values": []
        },
        {
            "property_id": 513,
            "name": "Custom1",
            "display_name": "Custom Property",
            "scales": [],
            "is_required": false,
            "supports_attributes": false,
            "supports_variations": true,
            "is_multivalued": false,
            "max_values_allowed": null,
            "possible_values": [],
            "selected_values": []
        },
        {
            "property_id": 514,
            "name": "Custom2",
            "display_name": "Custom Property",
            "scales": [],
            "is_required": false,
            "supports_attributes": false,
            "supports_variations": true,
            "is_multivalued": false,
            "max_values_allowed": null,
            "possible_values": [],
            "selected_values": []
        }
    ]
}
```


yes I can see it as customer (https://www.etsy.com/listing/1262384258/do-not-delete-or-modify-this-gio-github) but not as manager

**Comment by etsyachristensen** [comment]
Ok appreciate the follow-up. While the ID you are sending is probably valid in connection to the property, it's likely a custom ID that the interface can't track. When you send it using the taxonomy array value but then call to the `getListingProperties` endpoint does it return the custom value ID or the taxonomy value ID?

**Comment by hyyyper** [comment]
@etsyachristensen picking up where this left off...

`getListingProperties` will return the custom id.

In my case, there are no predefined value_ids to choose from.
**Width** set via the shop manager UI.
**Height** set via the API

```
{
    "count": 2,
    "results": [
        {
            "property_id": 47626759898,
            "property_name": "Width",
            "scale_id": 5,
            "scale_name": "Inches",
            "value_ids": [
                55911276088
            ],
            "values": [
                "5.5"
            ]
        },
        {
            "property_id": 47626759834,
            "property_name": "Height",
            "scale_id": 5,
            "scale_name": null,
            "value_ids": [
                12345678901  <-- custom id
            ],
            "values": [
                "1.6"
            ]
        }
    ]
}
```

**Comment by hyyyper** [comment]
A dropdown for the dimension scale, a text input for the value.
![image](https://user-images.githubusercontent.com/83091492/187476244-42a0034b-95aa-4639-9fec-7ee42aeb40a6.png)

![image](https://user-images.githubusercontent.com/83091492/187476357-939bd733-053a-4294-8314-f67780bd1b48.png)

**Comment by etsyachristensen** [comment]
Ah ok now I see. Thanks, I'll share this with our shop manager ui team.

**Comment by hyyyper** [comment]
Something to add...

I tried editing the listing via the shop manager UI.
After publishing, the `Height` was removed.

So, it seems the empty input causes the existing value to be removed.
This makes the issue a little more problematic.

**Comment by etsyachristensen** [comment]
I just noticed in the getProperties that the scale name is null. Can you re-update the listing with the height and the scale name? I see that width has the scale "Inches".

**Comment by etsyachristensen** [comment]
Also can you share the listing id?

**Comment by hyyyper** [comment]
listing_id: `1283770491`

I have tried providing the scale_name but AFAIK that's not a supported parameter on the `updateListingProperty` endpoint.

Here is the request params I have been sending:
![image](https://user-images.githubusercontent.com/83091492/187480317-5def2430-d2ad-49e7-a553-510e9ce3bb58.png)

Doc entry I'm referencing: https://developers.etsy.com/documentation/reference/#operation/updateListingProperty

**Comment by hyyyper** [comment]
Anything else I can do to help resolve this issue?

**Comment by etsyachristensen** [comment]
Sorry for the delay @hyyyper . I'm still working with the other teams here on this.
